use crate::asa_config_metadata::AsaConfigDefault;

use super::{DefaultValue, Target, default};

pub(super) const DEFAULTS: &[AsaConfigDefault] = &[
    default(
        "spectatorPassword",
        DefaultValue::Text(""),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "rconEnabled",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "hardcore",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "enablePvPGamma",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowHitMarkers",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "difficulty",
        DefaultValue::U32(5),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "xpMultiplier",
        DefaultValue::F64(1.5),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tamingSpeed",
        DefaultValue::U32(3),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "harvestAmount",
        DefaultValue::U32(2),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "harvestHealthMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "playerDamageMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "playerResistanceMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dinoDamageMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dinoResistanceMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tamedDinoDamageMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tamedDinoResistanceMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "playerFoodDrainMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "playerWaterDrainMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "playerStaminaDrainMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dinoFoodDrainMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dinoStaminaDrainMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "thirdPerson",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "crosshair",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "showMapPlayer",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "flyerCarry",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dayCycleSpeed",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dayTimeSpeed",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "nightTimeSpeed",
        DefaultValue::F64(1.5),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "resourceRespawn",
        DefaultValue::F64(0.7),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "resourceNoReplenishRadiusPlayers",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "resourceNoReplenishRadiusStructures",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dinoCount",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "maxTamedDinos",
        DefaultValue::U32(5000),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "supplyCrateLootQualityMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "fishingLootQualityMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "fuelConsumptionIntervalMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "itemStackSizeMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "globalSpoilingTimeMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "globalItemDecompositionTimeMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "globalCorpseDecompositionTimeMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "structureLimit",
        DefaultValue::U32(10500),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "disablePlacementCollision",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "pveStructureDecay",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowCaveBuildingPvE",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowCaveBuildingPvP",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "pveAllowStructuresAtSupplyDrops",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "enableExtraStructurePreventionVolumes",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "alwaysAllowStructurePickup",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowFlyingStaminaRecovery",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventDownloadItems",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventDownloadDinos",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventDownloadSurvivors",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventUploadItems",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventUploadDinos",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventUploadSurvivors",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "noTributeDownloads",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tributeCharacterExpirationSeconds",
        DefaultValue::U32(0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tributeDinoExpirationSeconds",
        DefaultValue::U32(0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tributeItemExpirationSeconds",
        DefaultValue::U32(0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "kickIdlePlayersPeriod",
        DefaultValue::U32(3600),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "rconBufferSize",
        DefaultValue::U32(6000),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventHibernation",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "stasisKeepControllers",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "useStructureStasisGrid",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "alwaysTickDedicatedSkeletalMeshes",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "adminLogging",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "chatLogging",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "crossArkAllowForeignDinoDownloads",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
];
