use crate::asa_config_metadata::AsaConfigDefault;

use super::{DefaultValue, Target, default};

pub(super) const DEFAULTS: &[AsaConfigDefault] = &[
    default(
        "spectatorPassword",
        DefaultValue::Text(""),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "rconEnabled",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "hardcore",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "enablePvPGamma",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowHitMarkers",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "difficulty",
        DefaultValue::U32(5),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "xpMultiplier",
        DefaultValue::F64(1.5),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tamingSpeed",
        DefaultValue::U32(3),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "harvestAmount",
        DefaultValue::U32(2),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "harvestHealthMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "playerDamageMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "playerResistanceMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dinoDamageMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dinoResistanceMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tamedDinoDamageMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tamedDinoResistanceMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "playerFoodDrainMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "playerWaterDrainMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "playerStaminaDrainMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dinoFoodDrainMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dinoStaminaDrainMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "thirdPerson",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "crosshair",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "showMapPlayer",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "flyerCarry",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dayCycleSpeed",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dayTimeSpeed",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "nightTimeSpeed",
        DefaultValue::F64(1.5),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "resourceRespawn",
        DefaultValue::F64(0.7),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "resourceNoReplenishRadiusPlayers",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "resourceNoReplenishRadiusStructures",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "dinoCount",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "maxTamedDinos",
        DefaultValue::U32(5000),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "supplyCrateLootQualityMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "fishingLootQualityMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "fuelConsumptionIntervalMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "itemStackSizeMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "globalSpoilingTimeMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "globalItemDecompositionTimeMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "globalCorpseDecompositionTimeMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "structureLimit",
        DefaultValue::U32(10500),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "disablePlacementCollision",
        DefaultValue::Bool(true),
        Target::GameIniShooterGameMode,
    ),
    default(
        "pveStructureDecay",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowCaveBuildingPvE",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowCaveBuildingPvP",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "pveAllowStructuresAtSupplyDrops",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "enableExtraStructurePreventionVolumes",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "alwaysAllowStructurePickup",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowFlyingStaminaRecovery",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventDownloadItems",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventDownloadDinos",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventDownloadSurvivors",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventUploadItems",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventUploadDinos",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventUploadSurvivors",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "noTributeDownloads",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tributeCharacterExpirationSeconds",
        DefaultValue::U32(0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tributeDinoExpirationSeconds",
        DefaultValue::U32(0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tributeItemExpirationSeconds",
        DefaultValue::U32(0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "kickIdlePlayersPeriod",
        DefaultValue::U32(3600),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "rconBufferSize",
        DefaultValue::U32(6000),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventHibernation",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default(
        "stasisKeepControllers",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default(
        "useStructureStasisGrid",
        DefaultValue::Bool(true),
        Target::LaunchArgument,
    ),
    default(
        "alwaysTickDedicatedSkeletalMeshes",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default(
        "adminLogging",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "chatLogging",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "crossArkAllowForeignDinoDownloads",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowHideDamageSourceFromLogs",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowMultipleAttachedC4",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowRaidDinoFeeding",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "clampItemSpoilingTimes",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "clampResourceHarvestDamage",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "destroyTamesOverSoftTameLimit",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "disableImprintDinoBuff",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "forceAllStructureLocking",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "globalVoiceChat",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventMateBoost",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventOfflinePvP",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventSpawnAnimations",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "proximityChat",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "pveDinoDecay",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "pvpDinoDecay",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "randomSupplyCratePoints",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "serverForceNoHud",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "showFloatingDamageText",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "showPlayerJoinNotifications",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "dinoHealthRecoveryMultiplier",
        DefaultValue::F64(1.0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "maxPersonalTamedDinos",
        DefaultValue::U32(0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "maxTamedDinosSoftTameLimit",
        DefaultValue::U32(5000),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "maxTamedDinosSoftTameLimitCountdown",
        DefaultValue::U32(604800),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "maxTributeDinos",
        DefaultValue::U32(20),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "maxTributeItems",
        DefaultValue::U32(50),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "oxygenSwimSpeedStatMultiplier",
        DefaultValue::F64(1.0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "platformSaddleBuildAreaBoundsMultiplier",
        DefaultValue::F64(1.0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "playerHealthRecoveryMultiplier",
        DefaultValue::F64(1.0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "preventOfflinePvPInterval",
        DefaultValue::F64(0.0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "pveDinoDecayPeriodMultiplier",
        DefaultValue::F64(1.0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "structureResistanceMultiplier",
        DefaultValue::F64(1.0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "customServerSettings",
        DefaultValue::Text(""),
        Target::GameUserSettingsServerSettings,
    ),
];
