use crate::asa_config_metadata::AsaConfigDefault;

use super::{DefaultValue, Target, default};

pub(super) const DEFAULTS: &[AsaConfigDefault] = &[
    default(
        "disableFriendlyFire",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "disableFriendlyFirePvP",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "cropGrowthSpeedMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "cropDecaySpeedMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "itemStackOverrides",
        DefaultValue::EmptyArray,
        Target::GameIniShooterGameMode,
    ),
    default(
        "matingInterval",
        DefaultValue::F64(0.25),
        Target::GameIniShooterGameMode,
    ),
    default(
        "matingSpeedMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "eggHatchSpeed",
        DefaultValue::U32(10),
        Target::GameIniShooterGameMode,
    ),
    default(
        "babyMatureSpeed",
        DefaultValue::U32(20),
        Target::GameIniShooterGameMode,
    ),
    default(
        "cuddleInterval",
        DefaultValue::F64(0.1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "babyFoodConsumption",
        DefaultValue::F64(0.5),
        Target::GameIniShooterGameMode,
    ),
    default(
        "layEggIntervalMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "babyCuddleGracePeriodMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "babyCuddleLoseImprintQualitySpeedMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "babyImprintingStatScaleMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "babyImprintAmountMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "allowAnyoneBabyImprintCuddle",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "platformStructureMultiplier",
        DefaultValue::F64(1.5),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "maxTribeSize",
        DefaultValue::U32(8),
        Target::GameIniShooterGameMode,
    ),
    default(
        "structureDamageRepairCooldown",
        DefaultValue::U32(180),
        Target::GameIniShooterGameMode,
    ),
    default(
        "structurePickupTimeAfterPlacement",
        DefaultValue::U32(30),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "structurePickupHoldDuration",
        DefaultValue::F64(0.5),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "autoDestroyOldStructuresMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "fastDecayUnsnappedCoreStructures",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "limitGeneratorsNum",
        DefaultValue::U32(3),
        Target::GameIniShooterGameMode,
    ),
    default(
        "limitGeneratorsRange",
        DefaultValue::U32(15000),
        Target::GameIniShooterGameMode,
    ),
    default(
        "allowCryoFridgeOnSaddle",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "disableCryopodEnemyCheck",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "disableCryopodFridgeRequirement",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "disableCryopodCooldown",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowSpeedLeveling",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "raidDinoFoodDrainMultiplier",
        DefaultValue::U32(1),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "minimumDinoReuploadInterval",
        DefaultValue::U32(0),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "enableDiseases",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "nonPermanentDiseases",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "tribeNameChangeCooldown",
        DefaultValue::U32(15),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "maxAlliancesPerTribe",
        DefaultValue::U32(0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "maxTribesPerAlliance",
        DefaultValue::U32(0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "limitBunkersPerTribe",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "limitBunkersPerTribeNum",
        DefaultValue::U32(3),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowBunkersInPreventionZones",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowRidingDinosInsideBunkers",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowBunkerModulesAboveGround",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowDinoAIInsideBunkers",
        DefaultValue::Bool(true),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowBunkerModulesInPreventionZones",
        DefaultValue::Bool(false),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "minDistanceBetweenBunkers",
        DefaultValue::U32(3000),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "enemyAccessBunkerHPThreshold",
        DefaultValue::F64(0.25),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "bunkerUnderHPThresholdDmgMultiplier",
        DefaultValue::F64(0.05),
        Target::GameUserSettingsServerSettings,
    ),
    default(
        "allowUnlimitedRespecs",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "disablePhotoMode",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "showCreativeMode",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "useDinoLevelUpAnimations",
        DefaultValue::Bool(true),
        Target::GameIniShooterGameMode,
    ),
    default(
        "disableWirelessCrafting",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "craftingSkillBonusMultiplier",
        DefaultValue::F64(1.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "craftXpMultiplier",
        DefaultValue::F64(1.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "customRecipeEffectivenessMultiplier",
        DefaultValue::F64(1.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "customRecipeSkillMultiplier",
        DefaultValue::F64(1.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "genericXpMultiplier",
        DefaultValue::F64(1.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "harvestXpMultiplier",
        DefaultValue::F64(1.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "killXpMultiplier",
        DefaultValue::F64(1.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "specialXpMultiplier",
        DefaultValue::F64(1.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "hairGrowthSpeedMultiplier",
        DefaultValue::F64(0.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "maxFallSpeedMultiplier",
        DefaultValue::F64(1.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "poopIntervalMultiplier",
        DefaultValue::F64(1.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "wildDinoFoodDrainMultiplier",
        DefaultValue::F64(1.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "photoModeRangeLimit",
        DefaultValue::F64(3000.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "wirelessCraftingRangeOverride",
        DefaultValue::F64(3000.0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "customGameIniSettings",
        DefaultValue::Text(""),
        Target::GameIniShooterGameMode,
    ),
];
