use crate::asa_config_metadata::AsaConfigDefault;

use super::{DefaultValue, Target, default};

pub(super) const DEFAULTS: &[AsaConfigDefault] = &[
    default(
        "disableFriendlyFire",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "cropGrowthSpeedMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "cropDecaySpeedMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "itemStackOverrides",
        DefaultValue::EmptyArray,
        Target::GameIniShooterGameMode,
    ),
    default(
        "matingInterval",
        DefaultValue::F64(0.25),
        Target::GameIniShooterGameMode,
    ),
    default(
        "matingSpeedMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "eggHatchSpeed",
        DefaultValue::U32(10),
        Target::GameIniShooterGameMode,
    ),
    default(
        "babyMatureSpeed",
        DefaultValue::U32(20),
        Target::GameIniShooterGameMode,
    ),
    default(
        "cuddleInterval",
        DefaultValue::F64(0.1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "babyFoodConsumption",
        DefaultValue::F64(0.5),
        Target::GameIniShooterGameMode,
    ),
    default(
        "layEggIntervalMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "babyCuddleGracePeriodMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "babyCuddleLoseImprintQualitySpeedMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "babyImprintingStatScaleMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "babyImprintAmountMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "allowAnyoneBabyImprintCuddle",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "platformStructureMultiplier",
        DefaultValue::F64(1.5),
        Target::GameIniShooterGameMode,
    ),
    default(
        "maxTribeSize",
        DefaultValue::U32(8),
        Target::GameIniShooterGameMode,
    ),
    default(
        "structureDamageRepairCooldown",
        DefaultValue::U32(180),
        Target::GameIniShooterGameMode,
    ),
    default(
        "structurePickupTimeAfterPlacement",
        DefaultValue::U32(30),
        Target::GameIniShooterGameMode,
    ),
    default(
        "structurePickupHoldDuration",
        DefaultValue::F64(0.5),
        Target::GameIniShooterGameMode,
    ),
    default(
        "autoDestroyOldStructuresMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "fastDecayUnsnappedCoreStructures",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "limitGeneratorsNum",
        DefaultValue::U32(3),
        Target::GameIniShooterGameMode,
    ),
    default(
        "limitGeneratorsRange",
        DefaultValue::U32(15000),
        Target::GameIniShooterGameMode,
    ),
    default(
        "allowCryoFridgeOnSaddle",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "disableCryopodEnemyCheck",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "disableCryopodFridgeRequirement",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "disableCryopodCooldown",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "allowSpeedLeveling",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "raidDinoFoodDrainMultiplier",
        DefaultValue::U32(1),
        Target::GameIniShooterGameMode,
    ),
    default(
        "minimumDinoReuploadInterval",
        DefaultValue::U32(0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "enableDiseases",
        DefaultValue::Bool(true),
        Target::GameIniShooterGameMode,
    ),
    default(
        "nonPermanentDiseases",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "tribeNameChangeCooldown",
        DefaultValue::U32(15),
        Target::GameIniShooterGameMode,
    ),
    default(
        "maxAlliancesPerTribe",
        DefaultValue::U32(0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "maxTribesPerAlliance",
        DefaultValue::U32(0),
        Target::GameIniShooterGameMode,
    ),
    default(
        "limitBunkersPerTribe",
        DefaultValue::Bool(true),
        Target::GameIniShooterGameMode,
    ),
    default(
        "limitBunkersPerTribeNum",
        DefaultValue::U32(3),
        Target::GameIniShooterGameMode,
    ),
    default(
        "allowBunkersInPreventionZones",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "allowRidingDinosInsideBunkers",
        DefaultValue::Bool(true),
        Target::GameIniShooterGameMode,
    ),
    default(
        "allowBunkerModulesAboveGround",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "allowDinoAIInsideBunkers",
        DefaultValue::Bool(true),
        Target::GameIniShooterGameMode,
    ),
    default(
        "allowBunkerModulesInPreventionZones",
        DefaultValue::Bool(false),
        Target::GameIniShooterGameMode,
    ),
    default(
        "minDistanceBetweenBunkers",
        DefaultValue::U32(3000),
        Target::GameIniShooterGameMode,
    ),
    default(
        "enemyAccessBunkerHPThreshold",
        DefaultValue::F64(0.25),
        Target::GameIniShooterGameMode,
    ),
    default(
        "bunkerUnderHPThresholdDmgMultiplier",
        DefaultValue::F64(0.05),
        Target::GameIniShooterGameMode,
    ),
];
