use crate::asa_config_metadata::AsaConfigDefault;

use super::{DefaultValue, Target, default};

pub(super) const DEFAULTS: &[AsaConfigDefault] = &[
    default(
        "allowFlyerSpeedLeveling",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default(
        "forceAllowCaveFlyers",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default(
        "whitelist",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default(
        "exclusiveJoin",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default(
        "useAllCores",
        DefaultValue::Bool(true),
        Target::LaunchArgument,
    ),
    default(
        "noBattlEye",
        DefaultValue::Bool(true),
        Target::LaunchArgument,
    ),
    default(
        "noTransferFromFiltering",
        DefaultValue::Bool(true),
        Target::LaunchArgument,
    ),
    default(
        "enableIdlePlayerKick",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default(
        "gbUsageToForceRestart",
        DefaultValue::U32(35),
        Target::LaunchArgument,
    ),
    default(
        "serverPlatform",
        DefaultValue::Text("ALL"),
        Target::LaunchArgument,
    ),
    default(
        "activeEvent",
        DefaultValue::Text(""),
        Target::LaunchArgument,
    ),
    default(
        "useDynamicConfig",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default(
        "customDynamicConfigUrl",
        DefaultValue::Text(""),
        Target::LaunchArgument,
    ),
    default(
        "clusterDirOverride",
        DefaultValue::Text("ShooterGame/Saved/clusters"),
        Target::LaunchArgument,
    ),
    default(
        "customLaunchArgs",
        DefaultValue::Text("-culture=zh"),
        Target::LaunchArgument,
    ),
    default(
        "serverGameLog",
        DefaultValue::Bool(true),
        Target::LaunchArgument,
    ),
    default(
        "serverGameLogIncludeTribe",
        DefaultValue::Bool(true),
        Target::LaunchArgument,
    ),
    default("noDinos", DefaultValue::Bool(false), Target::LaunchArgument),
    default(
        "noWildBabies",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default(
        "disableCustomCosmetics",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default(
        "unstasisDinoObstructionCheck",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default(
        "useServerNetSpeedCheck",
        DefaultValue::Bool(false),
        Target::LaunchArgument,
    ),
    default("noSound", DefaultValue::Bool(false), Target::LaunchArgument),
];
