import type { LogLine, ModItem, ServerConfig, ServerInstance } from './types'

export const initialInstances: ServerInstance[] = [
  { id: 'asa-01', name: 'ASA-01', map: 'The Island', mapCode: 'TheIsland_WP', mode: 'PvE', status: 'running', gamePort: 7777, queryPort: 27015, players: 24, maxPlayers: 30 },
  { id: 'asa-02', name: 'ASA-02', map: 'Scorched Earth', mapCode: 'ScorchedEarth_WP', mode: 'PvE', status: 'running', gamePort: 7787, queryPort: 27025, players: 18, maxPlayers: 30 },
  { id: 'asa-03', name: 'ASA-03', map: 'The Center', mapCode: 'TheCenter_WP', mode: 'PvE', status: 'running', gamePort: 7797, queryPort: 27035, players: 12, maxPlayers: 30 },
  { id: 'asa-04', name: 'ASA-04', map: 'Aberration', mapCode: 'Aberration_WP', mode: 'PvP', status: 'stopped', gamePort: 7807, queryPort: 27045, players: 0, maxPlayers: 30 },
  { id: 'asa-05', name: 'ASA-05', map: 'Extinction', mapCode: 'Extinction_WP', mode: 'PvE', status: 'running', gamePort: 7817, queryPort: 27055, players: 15, maxPlayers: 30 },
  { id: 'asa-06', name: 'ASA-06', map: 'Astraeos', mapCode: 'Astraeos_WP', mode: 'PvE', status: 'stopped', gamePort: 7827, queryPort: 27065, players: 0, maxPlayers: 30 },
  { id: 'asa-07', name: 'ASA-07', map: 'Ragnarok', mapCode: 'Ragnarok_WP', mode: 'PvE', status: 'running', gamePort: 7837, queryPort: 27075, players: 21, maxPlayers: 30 },
  { id: 'asa-08', name: 'ASA-08', map: 'Valguero', mapCode: 'Valguero_WP', mode: 'PvE', status: 'stopped', gamePort: 7847, queryPort: 27085, players: 0, maxPlayers: 30 },
  { id: 'asa-09', name: 'ASA-09', map: 'Lost Colony', mapCode: 'LostColony_WP', mode: 'PvE', status: 'stopped', gamePort: 7857, queryPort: 27095, players: 0, maxPlayers: 30 },
]

export const initialLogs: LogLine[] = [
  { id: 1, time: '16:45:12', instance: 'ASA-01', level: 'success', message: '启动成功，地图：The Island，玩家数：24/30' },
  { id: 2, time: '16:45:15', instance: 'ASA-02', level: 'info', message: '定时重启已开启，等待后台生效' },
  { id: 3, time: '16:45:23', instance: 'ASA-03', level: 'error', message: '实例未响应，已停止' },
  { id: 4, time: '16:45:30', instance: 'ASA-04', level: 'success', message: '玩家数量更新：44/60' },
  { id: 5, time: '16:45:42', instance: 'ASA-02', level: 'success', message: '自动备份完成，备份文件大小：2.1 GB' },
  { id: 6, time: '16:45:50', instance: 'ASA-04', level: 'success', message: '配置保存成功' },
  { id: 7, time: '16:46:02', instance: 'ASA-01', level: 'info', message: '玩家数量更新：25/30' },
]

export const initialMods: ModItem[] = [
  { id: '928708', name: 'Svartalfheim Armory', version: '1.18.2', size: '246 MB', enabled: true },
  { id: '929578', name: 'Utilities Plus', version: '4.7.0', size: '92 MB', enabled: true },
  { id: '926956', name: 'Super Spyglass Plus', version: '2.4.1', size: '31 MB', enabled: true, updateAvailable: true },
  { id: '930115', name: 'QoL+', version: '1.6.8', size: '508 MB', enabled: false },
]

export const defaultConfig: ServerConfig = {
  sessionName: '方舟进化 · 孤岛生存', serverPassword: '', spectatorPassword: '', adminPassword: 'ark-admin-2026', gamePort: 7777, queryPort: 27015,
  rconEnabled: true, rconPort: 32330, visibility: 'public', clusterId: 'Boat-ASA-Cluster', crossTransfer: true, maxPlayers: 30,
  pve: true, hardcore: false, disableFriendlyFire: false, enablePvPGamma: true, allowHitMarkers: true,
  difficulty: 5, xpMultiplier: 1.5, tamingSpeed: 3, harvestAmount: 2, harvestHealthMultiplier: 1,
  playerDamageMultiplier: 1, playerResistanceMultiplier: 1, dinoDamageMultiplier: 1, dinoResistanceMultiplier: 1,
  tamedDinoDamageMultiplier: 1, tamedDinoResistanceMultiplier: 1, playerFoodDrainMultiplier: 1, playerWaterDrainMultiplier: 1,
  playerStaminaDrainMultiplier: 1, dinoFoodDrainMultiplier: 1, dinoStaminaDrainMultiplier: 1,
  thirdPerson: true, crosshair: true, showMapPlayer: true, flyerCarry: true,
  autoRestart: true, restartTime: '04:00', saveInterval: 15, backupRetention: 7, autoUpdateServer: true, autoUpdateMods: true, restartOnCrash: true, saveOnStop: true,
  dayCycleSpeed: 1, dayTimeSpeed: 1, nightTimeSpeed: 1.5, resourceRespawn: 0.7,
  resourceNoReplenishRadiusPlayers: 1, resourceNoReplenishRadiusStructures: 1, dinoCount: 1, maxTamedDinos: 5000, destroyWildDinos: false,
  cropGrowthSpeedMultiplier: 1, cropDecaySpeedMultiplier: 1, supplyCrateLootQualityMultiplier: 1, fishingLootQualityMultiplier: 1,
  fuelConsumptionIntervalMultiplier: 1, itemStackSizeMultiplier: 1, globalSpoilingTimeMultiplier: 1,
  globalItemDecompositionTimeMultiplier: 1, globalCorpseDecompositionTimeMultiplier: 1,
  matingInterval: 0.25, matingSpeedMultiplier: 1, eggHatchSpeed: 10, babyMatureSpeed: 20, cuddleInterval: 0.1, babyFoodConsumption: 0.5,
  layEggIntervalMultiplier: 1, babyCuddleGracePeriodMultiplier: 1, babyCuddleLoseImprintQualitySpeedMultiplier: 1,
  babyImprintingStatScaleMultiplier: 1, babyImprintAmountMultiplier: 1, allowAnyoneBabyImprintCuddle: false,
  structureLimit: 10500, platformStructureMultiplier: 1.5, disablePlacementCollision: true, maxTribeSize: 8, tribeAlliances: true, pveStructureDecay: false,
  allowCaveBuildingPvE: false, allowCaveBuildingPvP: true, structureDamageRepairCooldown: 180,
  structurePickupTimeAfterPlacement: 30, structurePickupHoldDuration: 0.5, autoDestroyOldStructuresMultiplier: 1,
  fastDecayUnsnappedCoreStructures: false, limitGeneratorsNum: 3, limitGeneratorsRange: 15000,
  allowCryoFridgeOnSaddle: false, disableCryopodEnemyCheck: false, disableCryopodFridgeRequirement: false, disableCryopodCooldown: false,
  allowFlyerSpeedLeveling: false, forceAllowCaveFlyers: false, allowFlyingStaminaRecovery: false, raidDinoFoodDrainMultiplier: 1,
  whitelist: false, exclusiveJoin: false, preventDownloadItems: false, preventDownloadDinos: false, preventDownloadSurvivors: false,
  preventUploadItems: false, preventUploadDinos: false, preventUploadSurvivors: false, noTributeDownloads: false,
  minimumDinoReuploadInterval: 0, tributeCharacterExpirationSeconds: 0, tributeDinoExpirationSeconds: 0, tributeItemExpirationSeconds: 0,
  clusterDirOverride: 'ShooterGame/Saved/clusters', noTransferFromFiltering: true,
  enableIdlePlayerKick: false, kickIdlePlayersPeriod: 3600, enableDiseases: true, nonPermanentDiseases: false,
  tribeNameChangeCooldown: 15, maxAlliancesPerTribe: 0, maxTribesPerAlliance: 0,
  processPriority: 'aboveNormal', cpuAffinity: '自动', memoryWarningGb: 24, useAllCores: true, noBattlEye: true,
  networkTickRate: 30, maxClientRate: 100000, rconBufferSize: 6000, compressBackups: true, snapshotBeforeRestart: true,
  preventHibernation: false, stasisKeepControllers: false, useStructureStasisGrid: true, alwaysTickDedicatedSkeletalMeshes: false,
  gbUsageToForceRestart: 35, serverPlatform: 'ALL', activeEvent: '', useDynamicConfig: false, customDynamicConfigUrl: '',
  customLaunchArgs: '-culture=zh',
  serverGameLog: true, serverGameLogIncludeTribe: true, adminLogging: true, chatLogging: true, logTimestamp: true,
  logLevel: 'normal', rotateSizeMb: 100, logRetentionDays: 14, logPath: 'ShooterGame/Saved/Logs',
  crossArkAllowForeignDinoDownloads: false,
  limitBunkersPerTribe: true, limitBunkersPerTribeNum: 3, allowBunkersInPreventionZones: false,
  allowRidingDinosInsideBunkers: true, allowBunkerModulesAboveGround: false, allowDinoAIInsideBunkers: true,
  allowBunkerModulesInPreventionZones: false, minDistanceBetweenBunkers: 3000,
  enemyAccessBunkerHPThreshold: 0.25, bunkerUnderHPThresholdDmgMultiplier: 0.05,
}
