export const MAIN_WINDOW_LABEL = 'main'
export const ADD_INSTANCE_WINDOW_LABEL = 'add-instance'
export const RCON_WINDOW_LABEL_PREFIX = 'rcon'
export const ADD_INSTANCE_CREATED_EVENT = 'asa-instance-created'
export const SETTINGS_CHANGED_EVENT = 'asa-global-settings-changed'
